<x-layouts.print :title="'Receipt '.$payment->receipt_number">
    <div class="doc-header">
        <div>
            <p class="company-name">{{ setting('company_name', config('app.name')) }}</p>
            <p class="muted">{{ setting('company_address') }}</p>
            <p class="muted">{{ setting('company_phone') }} {{ setting('company_email') ? '· '.setting('company_email') : '' }}</p>
        </div>
        <div>
            <p class="doc-type">Receipt</p>
            <p style="text-align:right; font-weight:700;">{{ $payment->receipt_number }}</p>
            <p style="text-align:right;" class="muted">{{ $payment->payment_date->format('d M Y H:i') }}</p>
        </div>
    </div>

    <dl class="meta-grid">
        <div><dt>Received From</dt><dd>{{ $payment->invoice->customer->name }} ({{ $payment->invoice->customer->customer_code }})</dd></div>
        <div><dt>Invoice</dt><dd>{{ $payment->invoice->invoice_number }}</dd></div>
        <div><dt>Weight Ticket</dt><dd>{{ $payment->invoice->ticket->ticket_number }}</dd></div>
        <div><dt>Vehicle</dt><dd>{{ $payment->invoice->ticket->vehicle->plate_number }}</dd></div>
        <div><dt>Payment Method</dt><dd>{{ $payment->payment_method->label() }}</dd></div>
        <div><dt>Reference</dt><dd>{{ $payment->reference ?? '—' }}</dd></div>
    </dl>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align:right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Payment against invoice {{ $payment->invoice->invoice_number }}</td>
                <td style="text-align:right; font-weight:700; font-size:16px;">{{ money($payment->amount) }}</td>
            </tr>
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td>Invoice Total</td>
            <td style="text-align:right;">{{ money($payment->invoice->amount) }}</td>
        </tr>
        <tr>
            <td>Total Paid</td>
            <td style="text-align:right;">{{ money($payment->invoice->amount_paid) }}</td>
        </tr>
        <tr class="grand">
            <td>Balance</td>
            <td style="text-align:right;">{{ money($payment->invoice->outstanding) }}</td>
        </tr>
    </table>

    <div class="sign-row">
        <div class="sign-box">Received By — {{ $payment->receiver->name }}</div>
        <div class="sign-box">Customer Signature</div>
    </div>

    <p class="footer-note">Generated by {{ config('app.name') }} on {{ now()->format('d M Y H:i') }}</p>
</x-layouts.print>
