<x-layouts.print :title="'Invoice '.$invoice->invoice_number">
    <div class="doc-header">
        <div>
            <p class="company-name">{{ setting('company_name', config('app.name')) }}</p>
            <p class="muted">{{ setting('company_address') }}</p>
            <p class="muted">{{ setting('company_phone') }} {{ setting('company_email') ? '· '.setting('company_email') : '' }}</p>
        </div>
        <div>
            <p class="doc-type">Invoice</p>
            <p style="text-align:right; font-weight:700;">{{ $invoice->invoice_number }}</p>
            <p style="text-align:right;" class="muted">{{ $invoice->created_at->format('d M Y H:i') }}</p>
            @if ($invoice->status === \App\Enums\InvoiceStatus::Cancelled)
                <p style="text-align:right; color:#dc2626; font-weight:700; letter-spacing:2px;">CANCELLED</p>
            @endif
        </div>
    </div>

    <dl class="meta-grid">
        <div><dt>Billed To</dt><dd>{{ $invoice->customer->name }} ({{ $invoice->customer->customer_code }})</dd></div>
        <div><dt>Phone</dt><dd>{{ $invoice->customer->phone ?? '—' }}</dd></div>
        <div><dt>Weight Ticket</dt><dd>{{ $invoice->ticket->ticket_number }}</dd></div>
        <div><dt>Vehicle</dt><dd>{{ $invoice->ticket->vehicle->plate_number }}</dd></div>
    </dl>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align:right;">Net Weight (t)</th>
                <th style="text-align:right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Weighing service — {{ $invoice->ticket->product->name }}</td>
                <td style="text-align:right;">{{ number_format((float) $invoice->net_weight / 1000, 3) }}</td>
                <td style="text-align:right; font-weight:600;">{{ money($invoice->amount) }}</td>
            </tr>
        </tbody>
    </table>

    <table class="totals">
        <tr>
            <td>Total</td>
            <td style="text-align:right; font-weight:600;">{{ money($invoice->amount) }}</td>
        </tr>
        <tr>
            <td>Paid</td>
            <td style="text-align:right;">{{ money($invoice->amount_paid) }}</td>
        </tr>
        <tr class="grand">
            <td>Balance Due</td>
            <td style="text-align:right;">{{ money($invoice->outstanding) }}</td>
        </tr>
    </table>

    <div class="sign-row">
        <div class="sign-box">Issued By — {{ $invoice->creator->name }}</div>
        <div class="sign-box">Customer Signature</div>
    </div>

    <p class="footer-note">Generated by {{ config('app.name') }} on {{ now()->format('d M Y H:i') }}</p>
</x-layouts.print>
